### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by Kunkka99** [JAGJ10/PositionBasedFluids#1]
Hi,
 I've been trying to run the PositioBasedFluids-test demo ,But ...\PositionBasedFluids-test\PositionBasedFluids\meshes\bunny_closed_fixed.sdf  missed.Can you offer me that . Thanks a lot.

**Comment by JAGJ10** [comment]
Hey, that code is actually really just a WIP branch (which has a number of problems) and is probably out of date at this point. Not sure if I'll ever get around to updating it, but I don't even have that sdf file anymore.

That said, the sdf file is definitely not the best way of doing that.

Sorry about that!
