### ISSUE TITLE
Program crashed

### ISSUE THREAD

**Issue by Kunkka99** [JAGJ10/PositionBasedFluids#2]
Hi,I've been trying to run the PositioBasedFluids-master demo,It showed that the fragment complation_failed Then I changed the "final.frag"line35
 `float squiggly = clamp(sum * (vec3(1, 1, 1) - vec3(0, 0.2, 0.6)), 0, 1);
  fragColor = (1 - foamIntensity) * fluid + (foamIntensity * (0.9 - squiggly));`
to 
  `vec3 squiggly = clamp(sum * (vec3(1.0f, 1.0f, 1.0f) - vec3(0.0f, 0.2f, 0.6f)), 0.0f,1.0f);
  fragColor = (1 - foamIntensity) * fluid + vec4((foamIntensity * (0.9 - squiggly)),0.0f);`
now it can show the initial interface ,but when I run the fluid , my computer crasded.So I can't get the bug in detail. Maybe there is some problem in ParticleSystem.cu line 502-515.
My computer configuration：CPU intel 6700HQ, GPU GTX 960M,  win10 professional +vs2013+cuda8.0

**Comment by JAGJ10** [comment]
I've never tested with cuda 8.0 so there might be a problem with that. However, I have updated the "test" branch since you posted and it is now the most up to date version of the code. Might be worth giving that a try.
